name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Que se duerma el proceso
        run: sleep 4

      - name: A que hora ha terminado el despliegue chicos / as
        run: date

      - name: Quiero ver si mi página funciona
        run: curl -k "https://as.com"

      - name: Y ahora quiero saber con que version de git estoy trabajando
        run: git version